name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run tests
        working-directory: ./backend
        run: npm test

      - name: Build project
        run: npm run build
        working-directory: ./backend

      - name: Write SSH key to file
        run: echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem

      - name: Set file permissions
        run: chmod 600 ec2_key.pem

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST_DNS: ${{ secrets.HOST_DNS }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          ssh -i ec2_key.pem $USERNAME@$HOST_DNS "mkdir -p $TARGET_DIR"
          scp -i ec2_key.pem -r backend/dist/* $USERNAME@$HOST_DNS:$TARGET_DIR
          ssh -i ec2_key.pem $USERNAME@$HOST_DNS "pm2 restart all"
